name: CI/CD Pipeline

on:
  push:
    branches:
      - main

jobs:
  build_and_test:
    runs-on: self-hosted
    container:
      image: centos:9

    steps:
    - name: Checkout repository
      uses: actions/checkout@v2

    - name: Set up Node.js
      uses: actions/setup-node@v2
      with:
        node-version: 18

    - name: Install dependencies
      run: npm ci

    - name: Build
      run: npm run build

    # If you have tests, uncomment the following step
    #- name: Run tests
    #  run: npm test

  deploy:
    needs: build_and_test
    runs-on: ubuntu-latest
    if: github.ref == 'refs/heads/main'
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Install SSH client
      run: sudo apt-get install -y openssh-client

    - name: Setup SSH key
      env:
        PRIVATE_KEY: ${{ secrets.DEPLOY_SSH_PRIVATE_KEY }}
      run: |
        mkdir -p ~/.ssh
        echo "$PRIVATE_KEY" > ~/.ssh/id_rsa
        chmod 600 ~/.ssh/id_rsa
        echo -e "Host *\n\tStrictHostKeyChecking no\n\tUserKnownHostsFile /dev/null\n" > ~/.ssh/config

    - name: Deploy to server
      env:
        HOST: ${{ secrets.HOST }}
        USER: ${{ secrets.USER }}
        PORT: ${{ secrets.PORT }}
      run: |
        rsync -avz -e 'ssh -p $PORT' --exclude '.git' --exclude 'node_modules' . $USER@$HOST:~/home/user/apps/khanz1-docs
        ssh -p $PORT $USER@$HOST "cd ~/home/user/apps/khanz1-docs && npm ci && pm2 restart ecosystem.config.js"
